using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace API.Services.Entities
{
    /// <summary>
    /// This class represents a single course registration
    /// </summary>
    [Table("CourseRegistrations")]
    class CourseRegistration
    {
        /// <summary>
        /// ID of course registration generated by the database
        /// Example: 2
        /// </summary>
        public int ID { get; set; }
        /// <summary>
        /// The course ID of a course
        /// Example: 1
        /// </summary>
        public int CourseID { get; set; }

        /// <summary>
        /// The ID of a student
        /// Example: 1
        /// </summary>
        public int StudentID { get; set; }
    }
}
