using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace API.Services.Entities
{
    /// <summary>
    /// This class represents a single entry in the waiting list.
    /// </summary>
    [Table("WaitingList")]
    class WaitingListEntry
    {
        /// <summary>
        ///  The primary ID key of the entry. Generated by the database
        /// </summary>
        public int ID { get; set; }

        /// <summary>
        /// The course ID of a course generated by the database. Not null.
        /// Example: 1
        /// </summary>
        public int CourseID { get; set; }

        /// <summary>
        /// The ID of a student generated by the database. Not null.
        /// Example: 1
        /// </summary>
        public int StudentID { get; set; }       
    }
}
