using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace API.Services.Entities.Courses
{
    /// <summary>
    /// This class represents a single course template for a course
    /// </summary>
    [Table("CourseTemplates")]
    class CourseTemplate
    {
        /// <summary>
        /// The ID of a course generated by the database
        /// Example: 1
        /// </summary>
        public int ID { get; set; }

        /// <summary>
        ///  The ID of a course template.
        /// Example: "T-514-VEFT"
        /// </summary>
        public String TemplateID { get; set; }

        /// <summary>
        /// The name of a course
        /// Example: "Vefþjónustur"
        /// </summary>
        public String Name { get; set; }
    }
}
