using System.ComponentModel.DataAnnotations.Schema;


namespace API.Services.Entities.Courses
{
    /// <summary>
    /// This class represents a single course registration
    /// </summary>
    [Table("CourseRegistrations")]
    class CourseRegistration
    {
        /// <summary>
        /// ID of course registration generated by the database
        /// Example: 2
        /// </summary>
        public int ID { get; set; }
        
        /// <summary>
        /// The course ID of a course generated by the database. Not null.
        /// Example: 1
        /// </summary>
        public int CourseID { get; set; }

        /// <summary>
        /// The ID of a student generated by the database. Not null.
        /// Example: 1
        /// </summary>
        public int StudentID { get; set; }

        /// <summary>
        /// If the student is active in the course
        /// Example: true
        /// </summary>
        public bool Active { get; set; }
    }
}
